# This Dockerfile will be builded on DockerHub automated build configuration to create:
# - lorenzocalamandrei/angular-container:*.*.*-ci
# where *.*.* is the version of this Dockerfile
# The version will be taken from the tag by git.

# This Dockerfile extends:
# - lorenzocalamandrei/angular-container:*.*.*-base
ARG BASE_IMAGE=lorenzocalamandrei/angular-container:1.0.0-base
FROM ${BASE_IMAGE}

# install chrome for protractor tests
RUN echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN set -x \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        google-chrome-stable

USER node

ENV CHROME_BIN /usr/bin/google-chrome

# add `/var/www/html/node_modules/.bin` to $PATH
ENV PATH /var/www/html/node_modules/.bin:$PATH
